import React from "react";
import { styled } from "@mui/system";
import "./circle.css"
import {  Paper, Stack } from "@mui/material";
import bentmodule from "../../../public/assets/bentmodule.jpg"
const paperCss = {
   
    width:"200px",
    height:"150px",
    flexBasis: 'calc(90% / 3)',
    color: "#000",
    borderRadius: "40px",
    display:'flex',
    flexDirection:'column',
    justifyContent:'space-around',
    padding: "16px",
    fontSize: "15px",
    textAlign:"center",
    transition: 'transform 0.3s ease',
    '@media (max-width: 800px)': {
      flexBasis: 'calc(100% / 1)',
      '&:hover': {
        transform: 'scale(1)', // Change the hover effect for small screens
      }
    },
  }

const Phone = () => {
  return (
   <Stack direction={{md:'row',sm:'column',xs:'column'}} maxWidth={'1200px'} alignItems={'center'} justifyContent={'space-between'} spacing={5} padding={"36px 16px"}>
        <img src={bentmodule.src} alt="img" style={{height:"400px",width:"auto" ,border:"2px solid white", borderRadius:"40px"}} />
        <Stack direction={'row'} flexWrap={'wrap'} gap={3}>
            <Paper sx={paperCss} >
                <p className="text-xl font-bold">Ultralight weight</p>
                <p>Weight as low as 2.5 Kg/m2</p>
            </Paper>
            <Paper sx={paperCss} >
                <p className="text-xl font-bold">Flexibility</p>
                <p>The Sedi Modules are extremely flexible allowing them to conform to the substructure of the building or project</p>
            </Paper>
            <Paper sx={paperCss} >
                <p className="text-xl font-bold">Ultra-Slim design</p>
                <p>Our special manufacturing process  ensures that our solar panels are only 2-3mm thick</p>

            </Paper>
            <Paper sx={paperCss} >
                <p className="text-xl font-bold">Light behaviour</p>
                <p>Much better yield in low light and shadow.</p>
            </Paper>
            <Paper sx={paperCss} >
                <p className="text-xl font-bold">Ruggedized</p>
                <p>Shock absorbing, fully laminated surface provides high durability against weather, accidents or malicious attempts. </p>
            </Paper>
            <Paper sx={paperCss} >
                <p className="text-xl font-bold">High energy yield</p>
                <p>Light refraction effect generated by the lenticular surface.</p>
            </Paper>
            <Paper sx={paperCss} >
                <p className="text-xl font-bold">Easily mounted</p>
                <p>The modules can be glued, screwed or mounted onto the substructure.</p>
            </Paper>
            <Paper sx={paperCss} >
                <p className="text-xl font-bold">Project-specific solutions</p>
                <p>Module size, shape are entirely customizable to fit the contours of the project. </p>
            </Paper>
            <Paper sx={paperCss} >
                <p className="text-xl font-bold">Warranty</p>
                <p>Unsurpassed 25-year warranty and 40-year old performance warranty</p>
            </Paper>
        </Stack>
   </Stack>
  );
};

export default Phone;
